### ISSUE TITLE
Adapt the CMake build document it and get it in CI

### ISSUE THREAD

**Issue by ckormanyos** [Embedded-System-Lovers/WCH_V307_RISC-V#3]

**Comment by gdobato** [comment]
HI @ckormanyos ,
Issue should be implemented https://github.com/Embedded-System-Lovers/WCH_V307_RISC-V/pull/9
Let me know please if i overlooked anything
Thanks :)

**Comment by gdobato** [comment]
#9 needs still work

**Comment by ckormanyos** [comment]
> Issue should be implemented https://github.com/Embedded-System-Lovers/WCH_V307_RISC-V/pull/9
> Let me know please if i overlooked anything

Thanks Gabriel (@gdobato) The build looks fine and I can add the build job to the requirements for branch protection.
So the builds are formally correct, but the comments in #9 regarding stability of the run are noted.

I think maybe I'd say close this issue and deal with any remaining parts in a separate issue?

Cc: @Chalandi and @sajtkukac

**Comment by gdobato** [comment]
Thanks for the feedback @ckormanyos ,
I think it makes sense we keep this open till the runtime issue is solved, i assign it to myself
