### ISSUE TITLE
Compiler syncronization with Red Thing project

### ISSUE THREAD

**Issue by ckormanyos** [Embedded-System-Lovers/WCH_V307_RISC-V#5]
Hi Amine (@Chalandi),

I just tried the compiler you selected in this project on the [other Red Thing project](https://github.com/Embedded-System-Lovers/RED-V_SiFive_RISC-V_FE310_SoC) and it worked fine.

Do you believe it makes sense to use `10.2.0-risc-none-embed` on each project?

Cc: @gdobato and @sajtkukac

**Comment by Chalandi** [comment]
Hi Chris (@ckormanyos),

I built the OSEK RISC-V port branch with the toolchain `riscv-none-embed` and I tested it on the HW Target, It seems to work fine.

I think we can use it.

**Comment by ckormanyos** [comment]
> built the OSEK RISC-V port branch with the toolchain riscv-none-embed and I tested it on the HW Target, It seems to work fine.

> I think we can use it.

OK. Thanks for your insight Amine (@Chalandi). I'll take this discussion over to that repo.
